### ISSUE TITLE
Create and select a logo

### ISSUE THREAD

**Issue by tad124737337** [mozilla/uk-community#2]
As part of defining a brand for our community, we should have a logo.

Objective: #1 

**Steps**
- [x] Create a logo proposal
- [x] Request feedback from community
- [x] Make any changes needed, iterate
- [x] Publicise logo

**Comment by tad124737337** [comment]
@elioqoshi created a proposal for us.
![img_2015-10-21 11 27 30](https://cloud.githubusercontent.com/assets/1648878/10634036/d35dd4fa-77e6-11e5-80f7-d15c06b66048.jpg)

For Twitter etc:
![img_2015-10-21 11 27 45](https://cloud.githubusercontent.com/assets/1648878/10634040/d8cf09ea-77e6-11e5-8549-73b40ce7e5e1.jpg)

**Comment by elioqoshi** [comment]
The logo mark needs still a few tweaks but in general it will be the same as the ones Tom mentioned.

**Comment by tad124737337** [comment]
Will add feedback here
- [ ] Small missing piece under dino
- [ ] Use the top from the first design, looks more like a phone box

**Comment by gerv** [comment]
The missing horizontal bar also looks odd, but it would look odd to put it in too, because it would be very stubby each side. Can we add it in, and shrink the dino head a little to expose a bit more bar around it?

Also, what would it look like with a fourth row of windows? It seems a bit stubby for a phone box at the moment...

**Comment by elioqoshi** [comment]
@gerv I think you are getting a bit too literal here. The idea is to simplify it as much as possible. If we add that many details we could put in an actual phone box hehe.

**Comment by gerv** [comment]
I don't think it results in too much detail. Being precise about what you want doesn't necessarily result in a complex image. Here is a quick mockup:

![mozilla-uk](https://cloud.githubusercontent.com/assets/299746/10905882/2e070d94-8215-11e5-934f-1a72ad0523af.jpg)

This adds in the missing bars, which IMO looks much better. And it also adds an extra layer of windows so it's proportioned much more like a phone box. I didn't shrink the dino head; perhaps it would be OK without.

**Comment by elioqoshi** [comment]
You are right, that should look better. I will try this and slightly shrink the dino head just a bit. Thanks!

**Comment by tad124737337** [comment]
Check it out!

I've gone ahead and put this out publicly, given the largely positive feedback from the community. We made the changes suggested, but if you have small adjustments to suggest, we could totally make them.

Wanted something in time for MozFest :)

Leaving this open for a few days so people can give any suggestions.

![rgb-01](https://cloud.githubusercontent.com/assets/1648878/10965630/50cac644-83a6-11e5-91b2-02d21341be43.png)
![rgb-02](https://cloud.githubusercontent.com/assets/1648878/10965631/50d256b6-83a6-11e5-84a1-3a99899c726e.png)

**Comment by gerv** [comment]
I wonder if the dino might look better across the middle two rows rather than the top two? Could we see a sample to compare?

**Comment by elioqoshi** [comment]
@gerv here are 2 examples with the dino half row below, and one row below
![uk dino](https://cloud.githubusercontent.com/assets/5436686/10972153/3985a8c8-83d8-11e5-9bce-4c16b1715666.jpg)

**Comment by elioqoshi** [comment]
I must say I prefer the one with a half row more below

**Comment by gerv** [comment]
Yes, I like half row below - the one on the left - as well.

Gerv

**Comment by elioqoshi** [comment]
Will update this by Sunday

**Comment by bunnybooboo** [comment]
3 years later do we wish to have a refresh or use assets already built?
