### ISSUE TITLE
Research UK Community Members

### ISSUE THREAD

**Issue by tad124737337** [mozilla/uk-community#3]
We should research the things that our UK people envision/want from a community.

People are the focus and material of a community, so anything we do needs to work for and with their requirements.
- [x] MozLDN staff group interview
- [ ] Discussions at MozFest
- [ ] Group interview w/ UK volunteers
- [ ] Individual Interviews with selection of Mozillians
- [ ] Requirements document

**Comment by bunnybooboo** [comment]
Perhaps this issue needs some catch up to reflect activity in Discourse or closed?
