### ISSUE TITLE
Identify Mozillians in the UK

### ISSUE THREAD

**Issue by tad124737337** [mozilla/uk-community#4]
We should gather data on all of the Mozillians in the UK, so that we can track engagement and invite them to collaborate together
Useful info to gather is:
- Name
- Online Handles
- Contact info
- Last active
- First active

Some potential sources (keep this updated)
- [ ] Mozillians
- [ ] Reps portal
- [ ] GitHub
- [ ] SUMO

**Comment by tad124737337** [comment]
Will track people here:
https://docs.google.com/a/mozilla-community.org/spreadsheets/d/11rpq032skRRpcOhoqWH0CRjXpPu3BBuMg2Trxr69n_U/edit?usp=sharing

Access will be highly restricted for obvious reasons

**Comment by tad124737337** [comment]
Current plan for Mozillians:
- [ ] [Get API key](https://bugzilla.mozilla.org/show_bug.cgi?id=1223504)
- [ ] Leo to write script for pulling contact data
- [ ] Pull list of full name + email addresses
- [ ] [Send mass email](https://docs.google.com/a/mozilla-community.org/document/d/1sDIIRsERnxqmDXnJy4MV1qQLi1KANLKTbV5loQSibro/edit?usp=sharing) to collect contact info and authorisation

**Comment by bunnybooboo** [comment]
With ParSys knocking out sprint after sprint on integration of Fx SSO, RS256, PhoneBook & Mozillians - should this issue be closed or edited?
